name: Cache Dependencies Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-7593aa1

      - name: prime-cache-7593aa1
        run: |
          if [ -z "${{ steps.cache.outputs.cache-hit }}" ]; then
            echo "Cache miss"
          else
            echo "Cache hit"
          fi
